spring:
  thymeleaf:
    cache: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

kraft:
  api:
    client: ${KRAFT_API_CLIENT:real}
