spring:
  thymeleaf:
    cache: false
  jpa:
    properties:
      hibernate:
        format_sql: true

management:
  endpoint:
    health:
      show-details: always

kraft:
  api:
    client: ${KRAFT_API_CLIENT:mock}
    mock-latest-round: ${KRAFT_API_MOCK_LATEST_ROUND:0}
