CREATE TABLE winning_numbers (
    round         INT         NOT NULL,
    draw_date     DATE        NOT NULL,
    n1            INT         NOT NULL,
    n2            INT         NOT NULL,
    n3            INT         NOT NULL,
    n4            INT         NOT NULL,
    n5            INT         NOT NULL,
    n6            INT         NOT NULL,
    bonus_number  INT         NOT NULL,
    first_prize   BIGINT      NOT NULL,
    first_winners INT         NOT NULL,
    total_sales   BIGINT      NOT NULL,
    created_at    DATETIME    NOT NULL,
    CONSTRAINT pk_winning_numbers PRIMARY KEY (round),
    CONSTRAINT chk_wn_round_positive       CHECK (round > 0),
    CONSTRAINT chk_wn_n1_range             CHECK (n1 BETWEEN 1 AND 45),
    CONSTRAINT chk_wn_n2_range             CHECK (n2 BETWEEN 1 AND 45),
    CONSTRAINT chk_wn_n3_range             CHECK (n3 BETWEEN 1 AND 45),
    CONSTRAINT chk_wn_n4_range             CHECK (n4 BETWEEN 1 AND 45),
    CONSTRAINT chk_wn_n5_range             CHECK (n5 BETWEEN 1 AND 45),
    CONSTRAINT chk_wn_n6_range             CHECK (n6 BETWEEN 1 AND 45),
    CONSTRAINT chk_wn_bonus_range          CHECK (bonus_number BETWEEN 1 AND 45),
    CONSTRAINT chk_wn_n1_lt_n2             CHECK (n1 < n2),
    CONSTRAINT chk_wn_n2_lt_n3             CHECK (n2 < n3),
    CONSTRAINT chk_wn_n3_lt_n4             CHECK (n3 < n4),
    CONSTRAINT chk_wn_n4_lt_n5             CHECK (n4 < n5),
    CONSTRAINT chk_wn_n5_lt_n6             CHECK (n5 < n6),
    CONSTRAINT chk_wn_bonus_distinct       CHECK (bonus_number NOT IN (n1, n2, n3, n4, n5, n6)),
    CONSTRAINT chk_wn_first_prize_nonneg   CHECK (first_prize >= 0),
    CONSTRAINT chk_wn_first_winners_nonneg CHECK (first_winners >= 0),
    CONSTRAINT chk_wn_total_sales_nonneg   CHECK (total_sales >= 0)
);

CREATE INDEX idx_winning_numbers_draw_date ON winning_numbers (draw_date);
